#!/usr/bin/env python

import numpy as np

print ('\n## split ##')
a = np.arange(9)
print ('first:')
print (a)
print ('splite 3:')
b = np.split(a,3)
print (b)
print ('splite at 4,7:')
b = np.split(a,[4,7])
print (b)


print ('\n## hsplit ##')
harr = np.floor(10 * np.random.random((2, 6)))
print ('org:')
print(harr)
print ('hsplit')
print(np.hsplit(harr, 3))


print ('\n## vsplit ##')
a = np.arange(16).reshape(4,4)
print ('org:')
print (a)
print ('vsplit:')
b = np.vsplit(a,2)
print (b)


print ('\n## resize ##')
a = np.array([[1,2,3],[4,5,6]])
print ('first:')
print (a)
print (a.shape)
b = np.resize(a, (3,2))
print ('second:')
print (b)
print (b.shape)
print ('resize:')
b = np.resize(a,(3,3))
print (b)


print ('\n## append ##')
a = np.array([[1,2,3],[4,5,6]])
print ('org:')
print (a)
print ('append:')
print (np.append(a, [7,8,9]))
print ('append at axis.0')
print (np.append(a, [[7,8,9]],axis = 0))
print ('append at axis.1')
print (np.append(a, [[5,5,5],[7,8,9]],axis = 1))


print ('\n## insert ##')
a = np.array([[1,2],[3,4],[5,6]])
print ('org:')
print (a)
print ('insert at 3:')
print (np.insert(a,3,[11,12]))
print ('insert at axis.0:')
print (np.insert(a,1,[11],axis = 0))
print ('insert at axis.1:')
print (np.insert(a,1,11,axis = 1))


print ('\n## delete ##')
a = np.arange(12).reshape(3,4)
print ('org:')
print (a)
print ('delete at 5:')
print (np.delete(a,5))
print ('delete col.2')
print (np.delete(a,1,axis = 1))
print ('delete s_2:')
a = np.array([1,2,3,4,5,6,7,8,9,10])
print (np.delete(a, np.s_[::2]))


print ('\n## unique ##')
a = np.array([5,2,6,2,7,5,6,8,2,9])
print ('org:')
print (a)
print ('unique:')
u = np.unique(a)
print (u)
print ('unique with return_index:')
u,indices = np.unique(a, return_index = True)
print (indices)
print ('org:')
print (a)
print ('unique with return_inverse:')
u,indices = np.unique(a, return_inverse = True)
print (u)
print ('index:')
print (indices)
print ('reconstruct org data with index:')
print (u[indices])
print ('unique with return_counts:')
u,indices = np.unique(a, return_counts = True)
print (u)
print (indices)

